# Generated by Django 6.0.6 on 2026-07-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Test Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Test Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('questions', models.ManyToManyField(blank=True, related_name='tests', to='sections.question', verbose_name='Questions')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='sections.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'ordering': ['id'],
            },
        ),
    ]
